project_id = "cwngpcxxwvspcpkbxeax"

[functions.parse-lab-report]
verify_jwt = false

[functions.get-shared-patient-data]
verify_jwt = false

[functions.send-vitals-report]
verify_jwt = false

[functions.check-vital-alerts]
verify_jwt = false

[functions.identify-pill]
verify_jwt = false

[functions.check-care-alerts]
verify_jwt = false
