// Phase 3.2 — Audit log viewer (HIPAA + access logs).
import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";

export interface AuditEntry {
  id: string;
  user_id: string;
  patient_user_id: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  details: Record<string, unknown> | null;
  ip_address: string | null;
  created_at: string;
}

export interface PracticeAuditEntry {
  id: string;
  created_at: string;
  actor_user_id: string;
  actor_name: string | null;
  actor_email: string | null;
  action: string;
  resource_type: string;
  resource_id: string | null;
  patient_user_id: string | null;
  patient_name: string | null;
  ip_address: string | null;
}

/**
 * Tenant-wide access log for a hospital's own admins.
 *
 * The RLS policy on hipaa_audit_logs is auth.uid() = user_id, so reading the
 * table directly shows an admin only their own actions. This goes through a
 * security-definer function scoped to actors inside the given tenant — the
 * "who accessed what" view a compliance reviewer asks for, with no
 * cross-tenant visibility.
 */
export function usePracticeAuditLog(
  practiceId: string | null,
  opts?: { search?: string; limit?: number },
) {
  const { user } = useAuth();
  return useQuery({
    queryKey: ['practice-audit-log', practiceId, opts?.search ?? '', opts?.limit ?? 500],
    enabled: !!user && !!practiceId,
    queryFn: async (): Promise<PracticeAuditEntry[]> => {
      // Cast: this function is newer than the generated types file, which is
      // regenerated by Supabase tooling and must not be hand-edited.
      const { data, error } = await supabase.rpc('practice_audit_log', {
        _practice_id: practiceId,
        _search: opts?.search?.trim() || null,
        _limit: opts?.limit ?? 500,
      });
      if (error) throw error;
      return (data ?? []) as PracticeAuditEntry[];
    },
  });
}

export interface AuditPage {
  entries: AuditEntry[];
  total: number;
}

export function useAuditLog(opts?: {
  patientId?: string;
  action?: string;
  limit?: number;
  /** 1-based page, when the caller wants server-side paging instead of a slice. */
  page?: number;
  pageSize?: number;
  /** Skip the query entirely — for a page showing the tenant view instead. */
  enabled?: boolean;
}) {
  const { user } = useAuth();
  const page = opts?.page;
  const pageSize = opts?.pageSize ?? 25;
  return useQuery({
    queryKey: [
      "audit-log",
      opts?.patientId ?? null,
      opts?.action ?? null,
      page ?? null,
      page ? pageSize : (opts?.limit ?? 200),
    ],
    // The trail is append-only, so keep the page the reader is on in place
    // while the next one loads rather than blanking it.
    placeholderData: (previous) => previous,
    queryFn: async (): Promise<AuditPage> => {
      let q = supabase
        .from("hipaa_audit_logs")
        .select("*", page ? { count: "exact" } : undefined)
        .order("created_at", { ascending: false });
      if (page) {
        const start = (page - 1) * pageSize;
        q = q.range(start, start + pageSize - 1);
      } else {
        q = q.limit(opts?.limit ?? 200);
      }
      if (opts?.patientId) q = q.eq("patient_user_id", opts.patientId);
      if (opts?.action) q = q.eq("action", opts.action);
      const { data, error, count } = await q;
      if (error) throw error;
      return { entries: (data ?? []) as AuditEntry[], total: count ?? data?.length ?? 0 };
    },
    enabled: !!user && opts?.enabled !== false,
  });
}
