// practice_departments, practice_department_members and
// practice_patient_departments are newer than src/integrations/supabase/types.ts,
// which is generated by Supabase tooling and must not be hand-edited. The `as any`
// on .from() matches how practice_invitations is handled in usePractice.ts, and
// drops out once the types are regenerated.
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

export interface Department {
  id: string;
  practice_id: string;
  name: string;
  description: string | null;
  is_active: boolean;
  created_at: string;
}

export interface DepartmentMember {
  id: string;
  department_id: string;
  user_id: string;
  is_lead: boolean;
}

export interface StaffOverviewRow {
  user_id: string;
  name: string | null;
  email: string | null;
  role: string;
  status: string;
  departments: string[];
  leads_departments: string[];
  assigned_patient_count: number;
  has_tenant_wide_view: boolean;
}

export interface PatientOverviewRow {
  patient_user_id: string;
  name: string | null;
  email: string | null;
  is_active: boolean;
  share_all: boolean;
  connected_at: string;
  departments: string[];
  department_ids: string[];
  assigned_clinicians: string[];
}

/** Departments in a hospital tenant, plus who works in and leads each one. */
export function usePracticeDepartments(practiceId?: string | null) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const invalidate = () => {
    queryClient.invalidateQueries({ queryKey: ['practice-departments'] });
    queryClient.invalidateQueries({ queryKey: ['practice-staff-overview'] });
    queryClient.invalidateQueries({ queryKey: ['practice-patient-overview'] });
  };

  const departments = useQuery({
    queryKey: ['practice-departments', practiceId],
    enabled: !!practiceId,
    queryFn: async (): Promise<Department[]> => {
      const { data, error } = await supabase
        .from('practice_departments' as any)
        .select('id, practice_id, name, description, is_active, created_at')
        .eq('practice_id', practiceId!)
        .order('name');
      if (error) throw error;
      return (data ?? []) as unknown as Department[];
    },
  });

  const members = useQuery({
    queryKey: ['practice-departments', 'members', practiceId],
    enabled: !!practiceId,
    queryFn: async (): Promise<DepartmentMember[]> => {
      const { data, error } = await supabase
        .from('practice_department_members' as any)
        .select('id, department_id, user_id, is_lead')
        .eq('practice_id', practiceId!);
      if (error) throw error;
      return (data ?? []) as unknown as DepartmentMember[];
    },
  });

  const createDepartment = useMutation({
    mutationFn: async ({ name, description }: { name: string; description?: string }) => {
      if (!practiceId || !user) throw new Error('No hospital selected');
      const { error } = await supabase.from('practice_departments' as any).insert({
        practice_id: practiceId,
        name: name.trim(),
        description: description?.trim() || null,
        created_by: user.id,
      } as never);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Department created');
      invalidate();
    },
    onError: (e: Error) =>
      toast.error(
        e.message.includes('duplicate')
          ? 'A department with that name already exists'
          : e.message || 'Could not create the department',
      ),
  });

  const setDepartmentActive = useMutation({
    mutationFn: async ({ departmentId, isActive }: { departmentId: string; isActive: boolean }) => {
      const { error } = await supabase
        .from('practice_departments' as any)
        .update({ is_active: isActive } as never)
        .eq('id', departmentId);
      if (error) throw error;
    },
    onSuccess: () => invalidate(),
    onError: (e: Error) => toast.error(e.message || 'Could not update the department'),
  });

  const addMember = useMutation({
    mutationFn: async ({
      departmentId,
      userId,
      isLead,
    }: {
      departmentId: string;
      userId: string;
      isLead: boolean;
    }) => {
      if (!practiceId || !user) throw new Error('No hospital selected');
      const { error } = await supabase.from('practice_department_members' as any).insert({
        department_id: departmentId,
        practice_id: practiceId,
        user_id: userId,
        is_lead: isLead,
        added_by: user.id,
      } as never);
      if (error) throw error;
    },
    onSuccess: (_d, vars) => {
      toast.success(vars.isLead ? 'Sub-admin appointed' : 'Added to the department');
      invalidate();
    },
    onError: (e: Error) =>
      toast.error(
        e.message.includes('duplicate')
          ? 'That person is already in this department'
          : e.message || 'Could not add them',
      ),
  });

  const removeMember = useMutation({
    mutationFn: async (memberRowId: string) => {
      const { error } = await supabase
        .from('practice_department_members' as any)
        .delete()
        .eq('id', memberRowId);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Removed from the department');
      invalidate();
    },
    onError: (e: Error) => toast.error(e.message || 'Could not remove them'),
  });

  const setLead = useMutation({
    mutationFn: async ({ memberRowId, isLead }: { memberRowId: string; isLead: boolean }) => {
      const { error } = await supabase
        .from('practice_department_members' as any)
        .update({ is_lead: isLead } as never)
        .eq('id', memberRowId);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Department lead updated');
      invalidate();
    },
    // The database refuses this for anyone but the chief admin; surface why.
    onError: (e: Error) => toast.error(e.message || 'Could not change the department lead'),
  });

  return {
    departments: departments.data ?? [],
    members: members.data ?? [],
    isLoading: departments.isLoading || members.isLoading,
    createDepartment: createDepartment.mutateAsync,
    isCreating: createDepartment.isPending,
    setDepartmentActive: setDepartmentActive.mutateAsync,
    addMember: addMember.mutateAsync,
    removeMember: removeMember.mutateAsync,
    setLead: setLead.mutateAsync,
  };
}

/** Chief-admin roster: who works here and what their access rests on. */
export function usePracticeStaffOverview(practiceId?: string | null) {
  const query = useQuery({
    queryKey: ['practice-staff-overview', practiceId],
    enabled: !!practiceId,
    queryFn: async (): Promise<StaffOverviewRow[]> => {
      const { data, error } = await (supabase as any).rpc('practice_staff_overview', {
        _practice_id: practiceId,
      });
      if (error) throw error;
      return (data ?? []) as StaffOverviewRow[];
    },
  });
  return { staff: query.data ?? [], isLoading: query.isLoading };
}

/** Patients sharing with this tenant, scoped to what the caller oversees. */
export function usePracticePatientOverview(practiceId?: string | null) {
  const queryClient = useQueryClient();
  const query = useQuery({
    queryKey: ['practice-patient-overview', practiceId],
    enabled: !!practiceId,
    queryFn: async (): Promise<PatientOverviewRow[]> => {
      const { data, error } = await (supabase as any).rpc('practice_patient_overview', {
        _practice_id: practiceId,
      });
      if (error) throw error;
      return (data ?? []) as PatientOverviewRow[];
    },
  });

  const routeToDepartment = useMutation({
    mutationFn: async ({
      patientUserId,
      departmentId,
    }: {
      patientUserId: string;
      departmentId: string;
    }) => {
      const {
        data: { user },
      } = await supabase.auth.getUser();
      if (!practiceId || !user) throw new Error('No hospital selected');
      const { error } = await supabase.from('practice_patient_departments' as any).insert({
        practice_id: practiceId,
        department_id: departmentId,
        patient_user_id: patientUserId,
        assigned_by: user.id,
      } as never);
      if (error) throw error;
    },
    onSuccess: () => {
      toast.success('Patient routed to the department');
      queryClient.invalidateQueries({ queryKey: ['practice-patient-overview'] });
    },
    onError: (e: Error) =>
      toast.error(
        e.message.includes('duplicate')
          ? 'This patient is already under that department'
          : e.message || 'Could not route the patient',
      ),
  });

  return {
    patients: query.data ?? [],
    isLoading: query.isLoading,
    routeToDepartment: routeToDepartment.mutateAsync,
    isRouting: routeToDepartment.isPending,
  };
}
