import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { publicRoutes, PRIVATE_PREFIXES, ROOT, ORIGIN } from './public-routes.mjs';

export function buildSitemap() {
  const urls = publicRoutes().map((r) =>
    `  <url>\n    <loc>${ORIGIN}${r.path}</loc>\n    <lastmod>${r.lastmod}</lastmod>\n    <changefreq>${r.changefreq}</changefreq>\n    <priority>${r.priority}</priority>\n  </url>`);
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join('\n')}\n</urlset>\n`;
}

const AI_BOTS = ['GPTBot', 'OAI-SearchBot', 'ChatGPT-User', 'ClaudeBot', 'Claude-SearchBot', 'Claude-User',
  'PerplexityBot', 'Perplexity-User', 'Google-Extended', 'Applebot-Extended', 'Bingbot', 'Googlebot', 'DuckDuckBot'];

export function buildRobots() {
  const rules = PRIVATE_PREFIXES.filter((p) => p !== '/sign-up').flatMap((p) =>
    p === '/s' ? ['Disallow: /s$', 'Disallow: /s?'] : [`Disallow: ${p}`]);
  const body = ['Allow: /', ...rules].join('\n');
  const bots = AI_BOTS.map((b) => `User-agent: ${b}`).join('\n');
  return [
    '# GENERATED by scripts/seo/generate-sitemap.mjs from PRIVATE_PREFIXES. Do not edit by hand.',
    '# Public marketing, docs and legal pages are open to search and reputable AI',
    '# crawlers. Signed-in, per-user, share-link and token routes are disallowed AND',
    '# carry a noindex meta tag inside the app. /s is the read-only snapshot link',
    '# (the token lives in the fragment); the $ anchor keeps /sign-up and /sitemap open.',
    '',
    'User-agent: *',
    body,
    '',
    '# Named groups replace the * group, so the rules are repeated for each.',
    bots,
    body,
    '',
    `Sitemap: ${ORIGIN}/sitemap.xml`,
    '',
  ].join('\n');
}

if (process.argv[1] && process.argv[1].endsWith('generate-sitemap.mjs')) {
  writeFileSync(path.join(ROOT, 'public', 'sitemap.xml'), buildSitemap());
  writeFileSync(path.join(ROOT, 'public', 'robots.txt'), buildRobots());
  console.log('sitemap.xml and robots.txt written');
}
