ALTER POLICY "Patients can accept or decline pending records" ON public.clinician_patient_records TO authenticated;
ALTER POLICY "Clinicians can view active shares for their patients" ON public.document_shares TO authenticated;
ALTER POLICY "Users and shared clinicians can view documents" ON public.health_documents TO authenticated;
ALTER POLICY "Practice managers can create invitations" ON public.practice_invitations TO authenticated;
ALTER POLICY "Practice managers can delete invitations" ON public.practice_invitations TO authenticated;
ALTER POLICY "Practice managers can add members" ON public.practice_members TO authenticated;
ALTER POLICY "Practice managers can remove members" ON public.practice_members TO authenticated;
ALTER POLICY "Practice managers can update members" ON public.practice_members TO authenticated;
ALTER POLICY "Practice members can view members" ON public.practice_members TO authenticated;
ALTER POLICY "Managers can remove patients" ON public.practice_patient_access TO authenticated;
ALTER POLICY "Managers can update patient access" ON public.practice_patient_access TO authenticated;
ALTER POLICY "Members can add patients" ON public.practice_patient_access TO authenticated;
ALTER POLICY "Practice members can view patients" ON public.practice_patient_access TO authenticated;
ALTER POLICY "Managers manage assignments" ON public.practice_patient_assignments TO authenticated;
ALTER POLICY "Practice members read assignments in their practice" ON public.practice_patient_assignments TO authenticated;
ALTER POLICY "Managers can modify permissions" ON public.practice_role_permissions TO authenticated;
ALTER POLICY "Members can read their practice permissions" ON public.practice_role_permissions TO authenticated;
ALTER POLICY "Practice managers can update practice" ON public.practices TO authenticated;
ALTER POLICY "Practice owners can delete practice" ON public.practices TO authenticated;
ALTER POLICY "Clinicians can view shares by email or user_id" ON public.provider_shares TO authenticated;
ALTER POLICY "Clinicians create imports for shared patients" ON public.qhin_imports TO authenticated;
ALTER POLICY "Clinicians view shared patient imports" ON public.qhin_imports TO authenticated;